### PR TITLE
Stationary shadow in NeuButton

### PR DESCRIPTION
**Pull request by Dotrar**
## Status

**READY** / Needs testing _(I don't know how to do this other than just making sure example works)_

## Description

This change does two things:
1. Refactor: 
    a. abstract class `NeuButton` inwhich `NeuTextButton` and `NeuIconButton` derives from.
    b. fix animated builder so that it's not rebuilding every frame (pass in the child)
2. Add changes to button animation:
    a. change `offset` during animation so that the shadow looks stationary. this makes the effect that the button is moving relative to is background (previously, it was moving with the shadow.)
    b. Add a curve for `bounceInOut` so that the button has a greater "pop" effect (subjective and perhaps could be done via a parameter passed to the constructor instead).

## Old Button:
old-button
## New Button:
new-button

## Type of Change

putting "bug fix" because of the moving shadows.

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by Dotrar** [comment]
Also forgive me for any glaring mistakes because i am very new to dart / flutter, but I want to use NeuBrutalism in one of my projects so I'll try and give back any changes i make :)

**Comment by Dotrar** [comment]
ezgif com-video-to-gif

**Comment by deepraj02** [comment]
hey dude, thanks for the contribution.
I'll be merging this PR soon

**Review by deepraj02 — APPROVED** [review]
LGTM !

**Pull request merged**
